version: '3'
services:
    dbt-bq:
      build:
        context: .
        target: dbt-bigquery
      image: dbt/bigquery
      volumes:
        - .:/usr/app
        - ~/.dbt/:/root/.dbt/
        - ~/.google/credentials/ch.json:/.google/credentials/google_credentials.json
      network_mode: host